### PR TITLE
Support accentuated characters

### LINKED ISSUE #8: Bundled OpenSans doesn't support accentuated characters
The included version of the font doesn't support accentuated characters such as `é`. However, OpenSans supports this char.

### PR DESCRIPTION
**Pull request by coaxial**
Closes #8

### CODE REVIEW

**Comment by benbalter** [comment]
Per [the contributing guidelines](../blob/master/docs/CONTRIBUTING.md#how-to-propose-changes), if you are making visual changes, please include a screenshot of what the affected element looks like, both before and after.

**Comment by coaxial** [comment]
Sorry for the delay @benbalter, here are screenshots.

Before:
screenshot from 2018-05-09 16-42-44

After:
screenshot from 2018-05-09 16-43-21

**Comment by coaxial** [comment]
Not sure why the build fails, this PR doesn't modify the file it's complaining about.

**Comment by coaxial** [comment]
Pinging @benbalter

**Pull request merged**
